### ISSUE TITLE
Respond to "command line" style evaluation requests, sans @ mention

### ISSUE THREAD

**Issue by hostilefork** [gchiu/rebolbot#44]
It would be nice to be able to ask for evaluation requests with something as simple as starting one's message with `>>`.  So for example:

```
>> print "Hello World"
```

Could provoke the bot into responding with:

```
Hello World
```

Although Rebol3 is a sensible default, there are other languages (Red, Rebol2, IDEONE) that we might want to evaluate.  So putting a word identifying the language could do that:

```
ruby> puts "Hello World"
```

In order to make that easier, I've taken the table of languages from IDEone and named all the variants as legal Rebol word!s here:

https://gist.github.com/hostilefork/9616146

I'd suggest that implicitly making any non-Rebol code a raw string is a good idea.

Note that this does not suggest abandoning the **do** command, or the **do/ideone** command... merely providing a more convenient interface to the functionality.

**Comment by gchiu** [comment]
we now have >> so I'm closing this
