### ISSUE TITLE
Make RebolBot ignore multi-line messages starting with >>

### ISSUE THREAD

**Issue by hostilefork** [gchiu/rebolbot#47]
When people post multi-line transcripts from their local terminal, they often have >> at the start, and RebolBot errors on them.

Since RebolBot has a multi-line communication method with being addressed on the first line, how about it just ignore any >> message that isn't a single line?

**Comment by johnk-** [comment]
I had a think about this and yes, I agree. So @rebolbot do for multiline and >> for single line.
Anther option would just be to change the prompt from ">> " to "> " which has the added advantage of being one less character to type. Thoughts?

**Comment by hostilefork** [comment]
I prefer the consistency/look of >>... also > is interpreted in markdown as "quote", so best to keep as-is...

**Comment by johnk-** [comment]
Complete
